### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by chauve-dev** [x753/Content-Warning-More-Players#1]
We tried with some friends and it didn't work, the game is considered full at 4 players

**Comment by Enniota** [comment]
same

**Comment by kerogs** [comment]
same

**Comment by x753** [comment]
The developers limited the max number of players server-side because it was causing issues for them. They plan on fixing it later, for now you can just keep an eye on the Thunderstore page for Content Warning for when an equivalent mod comes back.

https://thunderstore.io/c/content-warning/
